runtime! debian.vim

"vim-plug
call plug#begin('~/.vim/weapon')

Plug 'vim-airline/vim-airline'
Plug 'joshdick/onedark.vim'
Plug 'luochen1990/rainbow'
Plug 'w0rp/ale', {'for':'java,c,cpp,cs,python,sql,xml,json,registry,conf,javascript,html,vue,css,sh,vim'} 
Plug 'cespare/vim-toml', {'for':'toml'} 
Plug 'maralla/completor.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mbbill/fencview'
Plug 'terryma/vim-multiple-cursors'
Plug 'preservim/nerdtree'

call plug#end()

"设置为24bit颜色模式
if (has("termguicolors"))
	set termguicolors
endif

"覆盖onedark默认配置
if (has("autocmd"))
	augroup colorextend
		autocmd!
		autocmd ColorScheme * call onedark#extend_highlight("Normal", { "bg": { "gui": "#000000" } })
	augroup END
endif
colorscheme onedark 
let g:airline_theme='onedark'

let g:rainbow_active = 1

"透明背景
set background=dark
hi Normal guibg=NONE ctermbg=NONE

"完善鼠标支持
if has("mouse_sgr")
	set ttymouse=sgr
else
	set ttymouse=xterm2
end

set clipboard=unnamed
set number		"行号
set hlsearch
set autochdir
set cursorline
set smartindent
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set matchtime=1
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)
set backspace=indent,eol,start
set directory=~/.vim/tmp
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,sjis,euc-jp,euc-kr,latin1
set ts=4
set sw=4

"set plugin

"keybind
noremap <silent> t :NERDTreeToggle<CR>
