# This script was generated by SVP 4 Manager.
# Check https://www.svp-team.com for more details.

import vapoursynth as vs
core = vs.get_core(threads=10)

core.std.LoadPlugin("D:\\Program\\mpv\\portable_config\\svp4\\svpflow1_vs.dll")
core.std.LoadPlugin("D:\\Program\\mpv\\portable_config\\svp4\\svpflow2_vs.dll")

clip = video_in
super_params     = "{pel:1,scale:{up:0},gpu:1,full:false,rc:true}"
analyse_params   = "{block:{w:32,overlap:1},main:{search:{coarse:{type:2,distance:-6,bad:{range:0}},type:2}},refine:[{thsad:4000}]}"
smoothfps_params = "{gpuid:11,rate:{num:2,den:1,abs:false},algo:21,mask:{cover:80},scene:{}}"

src_fps     = container_fps if container_fps>0.1 else 24
demo_mode   = 0
stereo_type = 0

########## BEGIN OF base.py ##########
# This file is a part of SmoothVideo Project (SVP) ver.4
# This is NOT the full Vapoursynth script, all used variables are defined via
# JScript code that generates the full script text.

def interpolate(clip):
# DO NOT REMOVE this comment
# input_um - original frame in 4:2:0
# input_m  - cropped and resized (if needed) frame
# input_m8 - input_m converted to 8-bit
    input_um = clip.resize.Point(format=vs.YUV420P8)
    input_m = input_um
    input_m8 = input_m

    super   = core.svp1.Super(input_m8,super_params)
    vectors = core.svp1.Analyse(super["clip"],super["data"],input_m8,analyse_params)
    smooth  = core.svp2.SmoothFps(input_m,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=input_um,fps=src_fps)
    smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)

    if demo_mode==1:
        return demo(input_m,smooth)
    else:
        return smooth

if stereo_type == 1:
    lf = interpolate(core.std.CropRel(clip,0,(int)(clip.width/2),0,0))
    rf = interpolate(core.std.CropRel(clip,(int)(clip.width/2),0,0,0))
    smooth = core.std.StackHorizontal([lf, rf])
elif stereo_type == 2:
    lf = interpolate(core.std.CropRel(clip,0,0,0,(int)(clip.height/2)))
    rf = interpolate(core.std.CropRel(clip,0,0,(int)(clip.height/2),0))
    smooth = core.std.StackVertical([lf, rf])
else:
    smooth =  interpolate(clip)
########### END OF base.py ###########


smooth.set_output()
